### ISSUE TITLE
Explanation of metrics

### ISSUE THREAD

**Issue by brokencode64** [trustpilot/beat-exporter#37]
Love the exporter, but is there somewhere with a good description of what each of the metrics tracks?

**Comment by shivas** [comment]
There is no official documentation (as far as I know) from Elastic team, but most of the important metrics are these:

```
# HELP filebeat_libbeat_output_events libbeat.output.events
# TYPE filebeat_libbeat_output_events untyped
filebeat_libbeat_output_events{type="acked"} 0
filebeat_libbeat_output_events{type="active"} 0
filebeat_libbeat_output_events{type="batches"} 0
filebeat_libbeat_output_events{type="dropped"} 0
filebeat_libbeat_output_events{type="duplicates"} 0
filebeat_libbeat_output_events{type="failed"} 0
```

If you feel like delving and figuring out everything, PR is welcome to update help messages of metrics

**Comment by dudicoco** [comment]
@shivas can you please advise on what's the difference between `filebeat_libbeat_output_events` and `filebeat_libbeat_pipeline_events`?

Also, which metric would indicate connection issues to logstash/elasticsearch?

Thanks!

**Comment by dudicoco** [comment]
Also there's `filebeat_filebeat_events`, to add some complication :)

**Comment by malake** [comment]
+1 here. I'm trying to understand how many messages we are collecting and sending but i'm not sure what's up from down.

**Comment by whoamiUNIX** [comment]
+1 agree would be great to have some documentation something like this https://github.com/ClusterLabs/ha_cluster_exporter/blob/master/doc/metrics.md
This can be good for inspiration.

**Comment by plef** [comment]
+1. A bit of semantics can be read out of the official [Kibana Filebeat monitoring built-in](https://www.elastic.co/guide/en/kibana/7.10/user/monitoring/images/monitoring-beats-detail.jpg), but that is just a screenshot with very limited explanatory potential.

**Comment by milnomada** [comment]
+1

**Comment by lucadelmonte** [comment]
+1

**Comment by GMartinez-Sisti** [comment]
This metric appears to be related to the events waiting to be sent: `filebeat_libbeat_pipeline_events{type="active"}`. I'm going to use this as an initial effort to monitor the filebeat queue (formatted for helm):

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "alert-rules.labels" . | nindent 4 }}
    {{- include "common-library.labels" . | nindent 4 }}
  name: alert-rules-filebeat
spec:
  groups:
    - name: alert-rules-filebeat
      rules:
        - alert: FileBeatQueueEmpty
          expr: |
            filebeat_libbeat_pipeline_events{type="active"} == 0
          for: 30m
          labels:
            severity: warning
          annotations:
            description: Filebeat queue is empty
        - alert: FileBeatQueueGrowing
          expr: |
            filebeat_libbeat_pipeline_events{type="active"} > 500 and
            delta(filebeat_libbeat_pipeline_events{type="active"}[15m]) > 0
          for: 15m
          labels:
            severity: warning
          annotations:
            description: |
              {{ `Filebeat queue is {{printf "%.0f" $value}} and growing` }}
```

![image](https://user-images.githubusercontent.com/19713226/134487093-2a827ed4-26e2-4c60-bcad-e55988c59c83.png)
